new Vue({
    el:'#app',
    data:{
        searchCity:'',//搜索的城市
        currentCity:'',//当前城市
        currentTime:'',//当前时间
        currentDate:'',//当前日期
        cityMain:{  //城市详细天气数据(最高温、最低温、日出时间、日落时间、湿度、气压、风速、紫外线、天气类型)
            maxTemp:'100°C',
            minTemp:'0°C',
            sunRise:'8:00',
            sunSet:'17:00',
            humidity:'41%',
            pressure:'997hPa',
            windSpeed:'3km/h',
            uv:'8',
            weatherType:'晴',
            weatherTypeIcon:'qi-100'
        },
        fiveDayLike:[ //五天气候(类型、温度、星期)
            {
                todayBefore:1,//一天之后
                dayOfWeekCH:'星期天',
                dayOfWeekEN:'Sunday',
                averageTemp:'20°C',
                weatherType:'',
                weatherIcon:'qi-100'
            },
            {
                todayBefore:2,//一天之后
                dayOfWeekCH:'星期一',
                dayOfWeekEN:'Monday',
                averageTemp:'21°C',
                weatherType:'',
                weatherIcon:'qi-100'
            },
            {
                todayBefore:3,//一天之后
                dayOfWeekCH:'星期二',
                dayOfWeekEN:'Tuesday',
                averageTemp:'19°C',
                weatherType:'',
                weatherIcon:'qi-100'
            },
            {
                todayBefore:4,//一天之后
                dayOfWeekCH:'星期三',
                dayOfWeekEN:'Wednesday',
                averageTemp:'22°C',
                weatherType:'',
                weatherIcon:'qi-100'
            },
            {
                todayBefore:5,//一天之后
                dayOfWeekCH:'星期四',
                dayOfWeekEN:'Thursday',
                averageTemp:'23°C',
                weatherType:'',
                weatherIcon:'qi-100'
            }
        ],
        hourlyLike:[ //当天未来天气(类型、温度、时间、风向)
            {
                time:'12:00',//三小时之后
                averageTemp:'21°C',
                weatherTypeIcon:'qi-100',
                windDirectionIcon:'southWesternWind',
                windSpeed:'3km/h'
            },
            {
                time:'15:00',//六小时之后
                averageTemp:'21°C',
                weatherTypeIcon:'qi-100',
                windDirectionIcon:'southWesternWind',
                windSpeed:'3km/h'
            },
            {
                time:'18:00',//九小时之后
                averageTemp:'21°C',
                weatherTypeIcon:'qi-100',
                windDirectionIcon:'southWesternWind',
                windSpeed:'3km/h'
            },
            {
                time:'21:00',//十二小时之后
                averageTemp:'21°C',
                weatherTypeIcon:'qi-100',
                windDirectionIcon:'southWesternWind',
                windSpeed:'3km/h'
            },
        ]
    },
    methods:{   //和风天气用户key:b38053db3dee4ae39586a04fbff4ff1c
        searchWeather(){
            
        },
        getWeatherMain(){
            let locationId=0;
            axios({
                method:'get',
                url:'https://geoapi.qweather.com/v2/city/lookup',//根据城市名字查询城市id
                params:{
                    location:'罗湖',     //无结果是404
                    key:'b38053db3dee4ae39586a04fbff4ff1c'
                }
            }).then(function(respose){
                console.log(this.searchCity)
                console.log(respose.data)
                let data=respose.data;
                console.log(data.location)
                if(data.code!=200){//请求错误
                    alert('请求错误')
                }
                else{
                    for(let i in data.location){
                        if(data.location[i].name===this.searchCity){
                            console.log('搜寻成功,id为'+data.location[i].id)
                            locationId=data.location[i].id;//找到城市或区id之后查找详细天气状况
                        }
                    }
                    if(locationId==0){
                        alert('找不到这个地方')
                    }
                }
            })
        },
    },
    }
)